package de.synex.bingo.util;

import de.synex.bingo.main.*;
import java.io.*;
import org.bukkit.configuration.file.*;
import org.bukkit.*;

public class ConfigLink
{
    Main main;
    FileConfiguration language;
    public String prefix;
    public String pluginstarted;
    public String pluginstopped;
    public String kickmsgwinOnePlayer;
    public String kickmsgwinTwoPlayer;
    public String FollowingTeamTeleported;
    public String T1OnePlayer;
    public String T1TwoPlayer;
    public String T2OnePlayer;
    public String T2TwoPlayer;
    public String T3OnePlayer;
    public String T3TwoPlayer;
    public String BoatName;
    public String StartMessage;
    public String ActionBar;
    public String nopermission;
    public String notavailable;
    public String gamewillstart;
    public String gamestartsin;
    public String gamestarts;
    public String gamealreadystarts;
    public String usagebingopl;
    public String noconsole;
    public String usagebingorestart;
    public String teleportedtop;
    public String mustbingoworld;
    public String nospectatortop;
    public String usagetop;
    public String bingoitemsinround;
    public String teamfounditemTeam1;
    public String teamfounditemTeam2;
    public String teamfounditemTeam3;
    public String yourteamfoundfollowingitemsalready;
    public String onlyingamecommand;
    public String usagebingo;
    public String usagebrestart;
    public String teamselectorInventoryTitle;
    public String teamselection;
    public String tablistheaderingame;
    public String tablistheaderlobby;
    public String tablistfooter;
    public String spectatorjoined;
    public String lobbyisfullkick;
    public String playerjoined;
    public String roundisrestartingkick;
    public String jointeam1;
    public String alreadyteam1;
    public String team1full;
    public String jointeam2;
    public String alreadyteam2;
    public String team2full;
    public String jointeam3;
    public String alreadyteam3;
    public String team3full;
    public String TablistTeam1Colour;
    public String TablistTeam2Colour;
    public String TablistTeam3Colour;
    public String TablistDefaultUserColour;
    public String TablistGamemasterColour;
    public String modtLobbyRow1;
    public String modtLobbyRow2;
    public String modtInGameRow1;
    public String modtInGameRow2;
    public String deathmessage;
    public String leftserveringame;
    public String leftserveringamespectator;
    public String leftserverlobby;
    public String gameisrestarting;
    public String chatformatTeam1;
    public String chatformatTeam2;
    public String chatformatTeam3;
    public String chatformatwithoutteam;
    public String chatcolourDefaultUser;
    public String chatcolourGamemaster;
    public String scoreboardTitle;
    public String scoreboardYourTeam;
    public String scoreboardTeam1;
    public String scoreboardTeam2;
    public String scoreboardTeam3;
    public String scoreboardNoTeam;
    public String usagestart;
    
    public ConfigLink(final Main pl) {
        this.language = (FileConfiguration)YamlConfiguration.loadConfiguration(new File("plugins/Bingo", "language.yml"));
        this.prefix = ChatColor.translateAlternateColorCodes('&', this.language.getString("prefix"));
        this.pluginstarted = ChatColor.translateAlternateColorCodes('&', this.language.getString("pluginstarted"));
        this.pluginstopped = ChatColor.translateAlternateColorCodes('&', this.language.getString("pluginstopped"));
        this.kickmsgwinOnePlayer = ChatColor.translateAlternateColorCodes('&', this.language.getString("kickmsgwinOnePlayer"));
        this.kickmsgwinTwoPlayer = ChatColor.translateAlternateColorCodes('&', this.language.getString("kickmsgwinTwoPlayer"));
        this.FollowingTeamTeleported = ChatColor.translateAlternateColorCodes('&', this.language.getString("FollowingTeamTeleported"));
        this.T1OnePlayer = ChatColor.translateAlternateColorCodes('&', this.language.getString("T1OnePlayer"));
        this.T1TwoPlayer = ChatColor.translateAlternateColorCodes('&', this.language.getString("T1TwoPlayer"));
        this.T2OnePlayer = ChatColor.translateAlternateColorCodes('&', this.language.getString("T2OnePlayer"));
        this.T2TwoPlayer = ChatColor.translateAlternateColorCodes('&', this.language.getString("T2TwoPlayer"));
        this.T3OnePlayer = ChatColor.translateAlternateColorCodes('&', this.language.getString("T3OnePlayer"));
        this.T3TwoPlayer = ChatColor.translateAlternateColorCodes('&', this.language.getString("T3TwoPlayer"));
        this.BoatName = ChatColor.translateAlternateColorCodes('&', this.language.getString("BoatName"));
        this.StartMessage = ChatColor.translateAlternateColorCodes('&', this.language.getString("StartMessage"));
        this.ActionBar = ChatColor.translateAlternateColorCodes('&', this.language.getString("ActionBar"));
        this.nopermission = ChatColor.translateAlternateColorCodes('&', this.language.getString("nopermission"));
        this.notavailable = ChatColor.translateAlternateColorCodes('&', this.language.getString("notavailable"));
        this.gamewillstart = ChatColor.translateAlternateColorCodes('&', this.language.getString("gamewillstart"));
        this.gamestartsin = ChatColor.translateAlternateColorCodes('&', this.language.getString("gamestartsin"));
        this.gamestarts = ChatColor.translateAlternateColorCodes('&', this.language.getString("gamestarts"));
        this.gamealreadystarts = ChatColor.translateAlternateColorCodes('&', this.language.getString("gamealreadystarts"));
        this.usagebingopl = ChatColor.translateAlternateColorCodes('&', this.language.getString("usagebingopl"));
        this.noconsole = ChatColor.translateAlternateColorCodes('&', this.language.getString("noconsole"));
        this.usagebingorestart = ChatColor.translateAlternateColorCodes('&', this.language.getString("usagebingorestart"));
        this.teleportedtop = ChatColor.translateAlternateColorCodes('&', this.language.getString("teleportedtop"));
        this.mustbingoworld = ChatColor.translateAlternateColorCodes('&', this.language.getString("mustbingoworld"));
        this.nospectatortop = ChatColor.translateAlternateColorCodes('&', this.language.getString("nospectatortop"));
        this.usagetop = ChatColor.translateAlternateColorCodes('&', this.language.getString("usagetop"));
        this.bingoitemsinround = ChatColor.translateAlternateColorCodes('&', this.language.getString("bingoitemsinround"));
        this.teamfounditemTeam1 = ChatColor.translateAlternateColorCodes('&', this.language.getString("teamfounditemTeam1"));
        this.teamfounditemTeam2 = ChatColor.translateAlternateColorCodes('&', this.language.getString("teamfounditemTeam2"));
        this.teamfounditemTeam3 = ChatColor.translateAlternateColorCodes('&', this.language.getString("teamfounditemTeam3"));
        this.yourteamfoundfollowingitemsalready = ChatColor.translateAlternateColorCodes('&', this.language.getString("yourteamfoundfollowingitemsalready"));
        this.onlyingamecommand = ChatColor.translateAlternateColorCodes('&', this.language.getString("onlyingamecommand"));
        this.usagebingo = ChatColor.translateAlternateColorCodes('&', this.language.getString("usagebingo"));
        this.usagebrestart = ChatColor.translateAlternateColorCodes('&', this.language.getString("usagebrestart"));
        this.teamselectorInventoryTitle = ChatColor.translateAlternateColorCodes('&', this.language.getString("teamselectorInventoryTitle"));
        this.teamselection = ChatColor.translateAlternateColorCodes('&', this.language.getString("teamselection"));
        this.tablistheaderingame = ChatColor.translateAlternateColorCodes('&', this.language.getString("tablistheaderingame"));
        this.tablistheaderlobby = ChatColor.translateAlternateColorCodes('&', this.language.getString("tablistheaderlobby"));
        this.tablistfooter = ChatColor.translateAlternateColorCodes('&', this.language.getString("tablistfooter"));
        this.spectatorjoined = ChatColor.translateAlternateColorCodes('&', this.language.getString("spectatorjoined"));
        this.lobbyisfullkick = ChatColor.translateAlternateColorCodes('&', this.language.getString("lobbyisfullkick"));
        this.playerjoined = ChatColor.translateAlternateColorCodes('&', this.language.getString("playerjoined"));
        this.roundisrestartingkick = ChatColor.translateAlternateColorCodes('&', this.language.getString("roundisrestartingkick"));
        this.jointeam1 = ChatColor.translateAlternateColorCodes('&', this.language.getString("jointeam1"));
        this.alreadyteam1 = ChatColor.translateAlternateColorCodes('&', this.language.getString("alreadyteam1"));
        this.team1full = ChatColor.translateAlternateColorCodes('&', this.language.getString("team1full"));
        this.jointeam2 = ChatColor.translateAlternateColorCodes('&', this.language.getString("jointeam2"));
        this.alreadyteam2 = ChatColor.translateAlternateColorCodes('&', this.language.getString("alreadyteam2"));
        this.team2full = ChatColor.translateAlternateColorCodes('&', this.language.getString("team2full"));
        this.jointeam3 = ChatColor.translateAlternateColorCodes('&', this.language.getString("jointeam3"));
        this.alreadyteam3 = ChatColor.translateAlternateColorCodes('&', this.language.getString("alreadyteam3"));
        this.team3full = ChatColor.translateAlternateColorCodes('&', this.language.getString("team3full"));
        this.TablistTeam1Colour = ChatColor.translateAlternateColorCodes('&', this.language.getString("TablistTeam1Colour"));
        this.TablistTeam2Colour = ChatColor.translateAlternateColorCodes('&', this.language.getString("TablistTeam2Colour"));
        this.TablistTeam3Colour = ChatColor.translateAlternateColorCodes('&', this.language.getString("TablistTeam3Colour"));
        this.TablistDefaultUserColour = ChatColor.translateAlternateColorCodes('&', this.language.getString("TablistDefaultUserColour"));
        this.TablistGamemasterColour = ChatColor.translateAlternateColorCodes('&', this.language.getString("TeablistGamemasterColour"));
        this.modtLobbyRow1 = ChatColor.translateAlternateColorCodes('&', this.language.getString("modtLobbyRow1"));
        this.modtLobbyRow2 = ChatColor.translateAlternateColorCodes('&', this.language.getString("modtLobbyRow2"));
        this.modtInGameRow1 = ChatColor.translateAlternateColorCodes('&', this.language.getString("modtInGameRow1"));
        this.modtInGameRow2 = ChatColor.translateAlternateColorCodes('&', this.language.getString("modtInGameRow2"));
        this.deathmessage = ChatColor.translateAlternateColorCodes('&', this.language.getString("deathmessage"));
        this.leftserveringame = ChatColor.translateAlternateColorCodes('&', this.language.getString("leftserveringame"));
        this.leftserveringamespectator = ChatColor.translateAlternateColorCodes('&', this.language.getString("leftserveringamespectator"));
        this.leftserverlobby = ChatColor.translateAlternateColorCodes('&', this.language.getString("leftserverlobby"));
        this.gameisrestarting = ChatColor.translateAlternateColorCodes('&', this.language.getString("gameisrestarting"));
        this.chatformatTeam1 = ChatColor.translateAlternateColorCodes('&', this.language.getString("chatformatTeam1"));
        this.chatformatTeam2 = ChatColor.translateAlternateColorCodes('&', this.language.getString("chatformatTeam2"));
        this.chatformatTeam3 = ChatColor.translateAlternateColorCodes('&', this.language.getString("chatformatTeam3"));
        this.chatformatwithoutteam = ChatColor.translateAlternateColorCodes('&', this.language.getString("chatformatwithoutteam"));
        this.chatcolourDefaultUser = ChatColor.translateAlternateColorCodes('&', this.language.getString("chatcolourDefaultUser"));
        this.chatcolourGamemaster = ChatColor.translateAlternateColorCodes('&', this.language.getString("chatcolourGamemaster"));
        this.scoreboardTitle = ChatColor.translateAlternateColorCodes('&', this.language.getString("scoreboardTitle"));
        this.scoreboardYourTeam = ChatColor.translateAlternateColorCodes('&', this.language.getString("scoreboardYourTeam"));
        this.scoreboardTeam1 = ChatColor.translateAlternateColorCodes('&', this.language.getString("scoreboardTeam1"));
        this.scoreboardTeam2 = ChatColor.translateAlternateColorCodes('&', this.language.getString("scoreboardTeam2"));
        this.scoreboardTeam3 = ChatColor.translateAlternateColorCodes('&', this.language.getString("scoreboardTeam3"));
        this.scoreboardNoTeam = ChatColor.translateAlternateColorCodes('&', this.language.getString("scoreboardNoTeam"));
        this.usagestart = ChatColor.translateAlternateColorCodes('&', this.language.getString("usagestart"));
        this.main = pl;
    }
}
